[package]
name = "eunzip"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"
license = "Unlicense OR MIT"

[dependencies]
zip = { version = "0.5.10", default-features = false, features = ["deflate"] }
encoding = "0.2.33"
structopt = "0.3.21"
crossbeam-channel = "0.5.0"
rayon = "1.5.0"
memmap = "0.7.0"
fs2 = "0.4.3"
anyhow = "1.0.38"

[build-dependencies]
structopt = "0.3.21"
encoding = "0.2.33"
anyhow = "1.0.38"
